import json
import os

filepath = 'backend/data/cars.json'
with open(filepath, 'r') as f:
    cars = json.load(f)

upcoming_data = [
    {
        "id": 1001,
        "slug": "proton-emas-7",
        "brand": "Proton",
        "brandSlug": "proton",
        "model": "e.MAS 7",
        "year": 2024,
        "type": "Electric",
        "bodyType": "suv",
        "body": "SUV",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": True,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "The Future of Proton EVs",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "The Proton e.MAS 7 is an upcoming electric SUV bringing advanced EV technology and striking design to the market. Launching soon in Nepal.",
        "images": ["https://images.unsplash.com/photo-1619767886558-efdc259b6e09?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "Automatic", "fuel": "Electric", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "Automatic", "Fuel": "Electric"},
        "pros": ["Zero Emissions", "Modern Design"],
        "cons": ["Charging infrastructure dependent"],
        "highlights": ["Upcoming EV", "Proton's First EV"],
        "thumb": "https://images.unsplash.com/photo-1619767886558-efdc259b6e09?auto=format&fit=crop&q=80&w=400"
    },
    {
        "id": 1002,
        "slug": "aion-ut",
        "brand": "AION",
        "brandSlug": "aion",
        "model": "UT",
        "year": 2024,
        "type": "Electric",
        "bodyType": "hatchback",
        "body": "Hatchback",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": True,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "Urban Commuter Electric",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "The AION UT is an upcoming electric hatchback perfect for urban environments, promising efficiency and futuristic styling.",
        "images": ["https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "Automatic", "fuel": "Electric", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "Automatic", "Fuel": "Electric"},
        "pros": ["Compact size", "Efficient"],
        "cons": ["Limited boot space"],
        "highlights": ["Urban EV", "AION Technology"],
        "thumb": "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&q=80&w=400"
    },
    {
        "id": 1003,
        "slug": "chery-qq3",
        "brand": "Chery",
        "brandSlug": "chery",
        "model": "QQ3",
        "year": 2024,
        "type": "Electric",
        "bodyType": "hatchback",
        "body": "Hatchback",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": True,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "Affordable Electric Mobility",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "Chery QQ3 brings ultra-affordable electric mobility with compact dimensions, making it the perfect city car.",
        "images": ["https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "Automatic", "fuel": "Electric", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "Automatic", "Fuel": "Electric"},
        "pros": ["Highly affordable", "Easy to park"],
        "cons": ["Basic features", "Limited range"],
        "highlights": ["City EV", "Budget Friendly"],
        "thumb": "https://images.unsplash.com/photo-1553440569-bcc63803a83d?auto=format&fit=crop&q=80&w=400"
    },
    {
        "id": 1004,
        "slug": "deepal-s05",
        "brand": "Deepal",
        "brandSlug": "deepal",
        "model": "S05",
        "year": 2024,
        "type": "Electric",
        "bodyType": "suv",
        "body": "SUV",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": True,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "Premium Electric SUV",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "Deepal S05 is a highly anticipated electric SUV with cutting-edge tech, luxurious interiors, and impressive range.",
        "images": ["https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "Automatic", "fuel": "Electric", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "Automatic", "Fuel": "Electric"},
        "pros": ["Premium design", "Advanced features"],
        "cons": ["Premium pricing expected"],
        "highlights": ["Premium EV", "Long Range"],
        "thumb": "https://images.unsplash.com/photo-1560958089-b8a1929cea89?auto=format&fit=crop&q=80&w=400"
    },
    {
        "id": 1005,
        "slug": "leapmotor-a10",
        "brand": "Leapmotor",
        "brandSlug": "leapmotor",
        "model": "A10",
        "year": 2024,
        "type": "Electric",
        "bodyType": "suv",
        "body": "SUV",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": True,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "Smart Electric SUV",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "Leapmotor A10 combines smart connectivity features with robust electric performance for the modern family.",
        "images": ["https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "Automatic", "fuel": "Electric", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "Automatic", "Fuel": "Electric"},
        "pros": ["Smart connectivity", "Spacious"],
        "cons": ["Brand awareness in Nepal"],
        "highlights": ["Smart EV", "Family SUV"],
        "thumb": "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?auto=format&fit=crop&q=80&w=400"
    },
    {
        "id": 1006,
        "slug": "omoda-4",
        "brand": "Omoda",
        "brandSlug": "omoda",
        "model": "4",
        "year": 2024,
        "type": "Electric",
        "bodyType": "suv",
        "body": "SUV",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": True,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "The Stylish EV",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "Omoda 4 features futuristic styling and advanced safety features, aiming to disrupt the compact electric SUV market.",
        "images": ["https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "Automatic", "fuel": "Electric", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "Automatic", "Fuel": "Electric"},
        "pros": ["Striking design", "High safety rating"],
        "cons": ["Polarizing looks"],
        "highlights": ["Futuristic Design", "Advanced Safety"],
        "thumb": "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&q=80&w=400"
    },
    {
        "id": 1007,
        "slug": "tata-punch-facelift",
        "brand": "Tata",
        "brandSlug": "tata",
        "model": "Punch Facelift",
        "year": 2024,
        "type": "Petrol",
        "bodyType": "suv",
        "body": "SUV",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": False,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "The Micro SUV, Refreshed",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "The Tata Punch Facelift brings updated styling, new features, and enhanced comfort to the popular micro-SUV segment.",
        "images": ["https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "MT", "fuel": "Petrol", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "MT", "Fuel": "Petrol"},
        "pros": ["High ground clearance", "5-Star Safety Expected"],
        "cons": ["Engine performance could be better"],
        "highlights": ["Refreshed Design", "Micro SUV"],
        "thumb": "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&q=80&w=400"
    },
    {
        "id": 1008,
        "slug": "tata-tiago-facelift",
        "brand": "Tata",
        "brandSlug": "tata",
        "model": "Tiago Facelift",
        "year": 2024,
        "type": "Petrol",
        "bodyType": "hatchback",
        "body": "Hatchback",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": False,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "Seriously Fun, Updated",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "The Tata Tiago Facelift brings a fresh face and new technology to the beloved hatchback, keeping it competitive and stylish.",
        "images": ["https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "MT", "fuel": "Petrol", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "MT", "Fuel": "Petrol"},
        "pros": ["Value for money", "Solid build quality"],
        "cons": ["Refinement could improve"],
        "highlights": ["Updated Tech", "Value Hatchback"],
        "thumb": "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&q=80&w=400"
    },
    {
        "id": 1009,
        "slug": "jetour-t2",
        "brand": "Jetour",
        "brandSlug": "jetour",
        "model": "T2",
        "year": 2024,
        "type": "Petrol",
        "bodyType": "suv",
        "body": "SUV",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": False,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "Rugged SUV Capable",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "Jetour T2 offers rugged boxy styling combined with modern comforts, aimed at lifestyle SUV buyers looking for adventure.",
        "images": ["https://images.unsplash.com/photo-1621007947382-bb3c3994e3fd?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "Automatic", "fuel": "Petrol", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "Automatic", "Fuel": "Petrol"},
        "pros": ["Rugged looks", "Spacious"],
        "cons": ["Fuel efficiency might be low"],
        "highlights": ["Off-road Styling", "Feature Rich"],
        "thumb": "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fd?auto=format&fit=crop&q=80&w=400"
    },
    {
        "id": 1010,
        "slug": "baic-bj30",
        "brand": "BAIC",
        "brandSlug": "baic",
        "model": "BJ30",
        "year": 2024,
        "type": "Hybrid",
        "bodyType": "suv",
        "body": "SUV",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": False,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "Tough Hybrid SUV",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "The BAIC BJ30 is a tough, adventure-ready SUV that incorporates a hybrid powertrain for better efficiency without compromising capability.",
        "images": ["https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "Automatic", "fuel": "Hybrid", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "Automatic", "Fuel": "Hybrid"},
        "pros": ["Hybrid efficiency", "Tough design"],
        "cons": ["Brand network"],
        "highlights": ["Hybrid Tech", "Adventure Ready"],
        "thumb": "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=80&w=400"
    },
    {
        "id": 1011,
        "slug": "arcfox-alpha",
        "brand": "Arcfox",
        "brandSlug": "arcfox",
        "model": "Alpha",
        "year": 2024,
        "type": "Electric",
        "bodyType": "suv",
        "body": "SUV",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": True,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "Premium Electric Intelligence",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "Arcfox Alpha is a premium intelligent electric vehicle offering a serene driving experience, ultra-long range, and next-gen autonomy features.",
        "images": ["https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "Automatic", "fuel": "Electric", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "Automatic", "Fuel": "Electric"},
        "pros": ["High-tech features", "Luxurious interior"],
        "cons": ["High price tag expected"],
        "highlights": ["Premium Luxury", "Next-Gen Tech"],
        "thumb": "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&q=80&w=400"
    },
    {
        "id": 1012,
        "slug": "toyota-rav4-hybrid",
        "brand": "Toyota",
        "brandSlug": "toyota",
        "model": "RAV4 Hybrid",
        "year": 2024,
        "type": "Hybrid",
        "bodyType": "suv",
        "body": "SUV",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": False,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "Legendary SUV, Now Hybrid",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "The highly anticipated Toyota RAV4 Hybrid brings Toyota's proven hybrid technology to their globally best-selling SUV, offering power and efficiency.",
        "images": ["https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "CVT", "fuel": "Hybrid", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "CVT", "Fuel": "Hybrid"},
        "pros": ["Toyota reliability", "Excellent fuel economy"],
        "cons": ["Availability delays possible"],
        "highlights": ["Toyota Reliability", "Hybrid Power"],
        "thumb": "https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&q=80&w=400"
    },
    {
        "id": 1013,
        "slug": "hongqi-e-hs9",
        "brand": "Hongqi",
        "brandSlug": "hongqi",
        "model": "E-HS9",
        "year": 2024,
        "type": "Electric",
        "bodyType": "suv",
        "body": "SUV",
        "badge": "Upcoming",
        "budgetTier": "TBD",
        "isEV": True,
        "isNew": True,
        "isFeatured": False,
        "isBestSeller": False,
        "tagline": "The Pinnacle of Luxury",
        "rating": 0,
        "reviews": 0,
        "expertScore": 0,
        "baseEMI": 0,
        "overview": "Hongqi E-HS9 is a massive, ultra-luxurious electric SUV offering a Rolls-Royce-like presence and unmatched interior opulence.",
        "images": ["https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&q=80&w=1200"],
        "colors": [],
        "variants": [{"name": "Standard", "slug": "standard", "price": 0, "label": "Base", "popular": True, "transmission": "Automatic", "fuel": "Electric", "features": ["TBD"], "specs": {}}],
        "specs": {"Transmission": "Automatic", "Fuel": "Electric"},
        "pros": ["Incredible road presence", "Ultra luxury"],
        "cons": ["Very expensive", "Massive size"],
        "highlights": ["Ultra Luxury", "Massive Presence"],
        "thumb": "https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&q=80&w=400"
    }
]

# Filter out if they already exist
existing_slugs = {c['slug'] for c in cars}
for u in upcoming_data:
    if u['slug'] not in existing_slugs:
        cars.append(u)

with open(filepath, 'w') as f:
    json.dump(cars, f, indent=2)

print(f"Added upcoming cars. Total cars now: {len(cars)}")
